anuncio_index:
    path:     /
    defaults: { _controller: "MainBundle:Anuncio:index" }
    methods:  GET

anuncio_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Anuncio:show" }
    methods:  GET

anuncio_new:
    path:     /new
    defaults: { _controller: "MainBundle:Anuncio:new" }
    methods:  [GET, POST]

anuncio_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Anuncio:edit" }
    methods:  [GET, POST]

anuncio_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Anuncio:delete" }
    methods:  DELETE
