video_index:
    path:     /
    defaults: { _controller: "MainBundle:Video:index" }
    methods:  GET

video_show:
    path:     /{id}/show
    defaults: { _controller: "MainBundle:Video:show" }
    methods:  GET

video_new:
    path:     /new
    defaults: { _controller: "MainBundle:Video:new" }
    methods:  [GET, POST]

video_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBundle:Video:edit" }
    methods:  [GET, POST]

video_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBundle:Video:delete" }
    methods:  DELETE
